### PR TITLE
Fix incorrect English in warning message

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by leejo** [comment]
Rejecting for three reasons:

1) In the context of the error message there is no ambiguity as to what "none supported" means here, and it is arguable whether or not this is incorrect English in domain of software given "none supported" or "not supported" are common colloquialisms/jargon therein.

2) (More important) This will create needless churn in the repo history as it will add a second layer of abstraction away from the original change, witness:

```
437f3caf lib/CGI.pm (Lee Johnson               2015-02-13 08:56:42 +0100  931)
437f3caf lib/CGI.pm (Lee Johnson               2015-02-13 08:56:42 +0100  932)  if ( /^[:-]any$/ ) {
437f3caf lib/CGI.pm (Lee Johnson               2015-02-13 08:56:42 +0100  933)          warn "CGI -any pragma has been REMOVED. You should audit your code for any use "
437f3caf lib/CGI.pm (Lee Johnson               2015-02-13 08:56:42 +0100  934)                  . "of none supported / incorrectly spelled tags and remove them"
437f3caf lib/CGI.pm (Lee Johnson               2015-02-13 08:56:42 +0100  935)          ;
437f3caf lib/CGI.pm (Lee Johnson               2015-02-13 08:56:42 +0100  936)          next;
437f3caf lib/CGI.pm (Lee Johnson               2015-02-13 08:56:42 +0100  937)  }
```

Changing the error message will introduce a new commit in the blame, no longer having a direct reference to the original commit (437f3caf)

3) (Most important) - it is possible that someone may have written regression tests to look for this specific string in changes to their own code, this change could either break those tests and/or have them unexpectedly pass (a false +ve).

So thanks for the tweak but with CGI.pm I am trying to avoid all unnecessary tweaks/refactoring/churn, as per the contributing guide: https://github.com/leejo/CGI.pm/blob/master/CONTRIBUTING.md

**Comment by rrthomas** [comment]
"none supported" can be correct standalone (e.g. "non-standard tags: none supported"), but not as an adjective phrase, jargon or not. This sort of mistake is commonly made by non-native speakers of English in my experience. "not supported" is less ambiguous, but still only correct as a complement (e.g. "foo is not supported"✓) and not as a modifier ("foo is a not supported option"✗, though "foo is not a supported option"✓).

The blame will only change for that particular line; it will still be obvious in the surrounding lines. And, as I say, it's not "needless", it's a matter of not confusing users of CGI.pm, or making them take extra time to understand what it's saying.

Matching against the entire warning seems unlikely to me (rather than e.g. "CGI -any pragma has been removed."), but fair enough!

**Comment by leejo** [comment]
Thanks :) - I make these mistakes often BTW, as my first language is slowly being eroded by a second. Example: https://github.com/leejo/business-monzo/commit/c29377f37d9ca8443e7bd74ae7af9efee61b5ec7 # in which i correct the spurious use of "e" but make the same mistake in the commit subject.

(Usually i *would* accept this PR, but with CGI.pm I'm being particularly strict about churn in the repo).

**Comment by rrthomas** [comment]
Ha! Yes, I find myself sometimes having to "interpret" the English of friends who've lived a long time in France for the benefit of non-French–speakers. I wasn't there long enough myself.

**Pull request closed without merging**
