### PR TITLE
Tests and documentation for command line mode

### PR DESCRIPTION
**Pull request by epa**
I understand that CGI.pm is in feature freeze so no new features will be added.  I understand however that you accept and welcome additional test coverage or improved documentation.  Please consider this pull request which tests and documents the command-line mode of CGI.pm.

### CODE REVIEW

**Comment by leejo** [comment]
Merged, thanks!

**Comment by epa** [comment]
I think there might be some additional dependency for the test case that needs adding to Makefile.PL.  Sorry I forgot that but it came up with the earlier (now reverted) pull request.

**Comment by leejo** [comment]
OK, reverted! #216 

Might be worth checking how well this test works on Windows based systems as well. Can't see any reason why it should be a problem but...

**Comment by epa** [comment]
I think it is safe to merge, since an additional dependency at the testing stage cannot affect any production systems, but if you have a 'no new build dependencies' policy let me know and I will make sure the test case doesn't bring in any new ones.

**Comment by leejo** [comment]
No, the dependency needs to be in the Makefile.PL otherwise tests will fail when installing the module from CPAN due to the missing dependency. IIRC this was the problem last time.

**Comment by epa** [comment]
I've pushed a new commit adding the dependency but I don't know how to get it into this pull request.

**Comment by leejo** [comment]
Bring your branch up to date with master here then open another PR.

**Pull request merged**
