### PR TITLE
Documentation and test for command line mode

### PR DESCRIPTION
**Pull request by epa**
As discussed.  In the end I made a clean fork of the upstream repository and reapplied my changes.

### CODE REVIEW

**Comment by leejo** [comment]
OK, merged! Thanks again.

**Comment by epa** [comment]
Thanks.  Is there any hope that the strict feature freeze will be relaxed in future?  Perhaps under a different module name?

**Comment by leejo** [comment]
> Thanks. Is there any hope that the strict feature freeze will be relaxed in future? Perhaps under a different module name?

You're more than welcome to fork the module to a different namespace.

**Comment by epa** [comment]
There is CGI::Simple which looks like the successor to this module, combined with HTML::Tiny.

**Pull request merged**
