### PR TITLE
use $r->err_headers_out

### PR DESCRIPTION
**Pull request by sherrardb**

### CODE REVIEW

**Comment by leejo** [comment]
w/r/t #240

@sherrardb - thanks. How much testing have you done with this? Have you dropped the patch in your app showing the issue and confirmed it's good? I ask because it appears this line of code has been tweaked previously in d7c964899a48def91f35ea0263447f1c90ad5a00, suggesting it was working at one point (or perhaps that wasn't *quite* the same use case?).

**Comment by sherrardb** [comment]
i actually "started" with the long-form version

```
$r->err_headers_out->add('Set-Cookie' => $cookie->as_string);
```
based on looking in the libapreq source,

```
void ApacheCookie_bake(ApacheCookie *c)
{
    ap_table_add(c->r->err_headers_out, "Set-Cookie",
                 ApacheCookie_as_string(c));
}
```

and then worked backwards, eventually discovering why neither `CGI::Cookie->bake( $r )`, nor the snippet in the POD were working for me.

so d7c9648 was definitely necessary, as (i'm pretty sure) multiple calls to `bake()` would have "eaten" the previous cookies (pun intended). but that patch is unrelated to my issue, which involves redirects. ie, with the following workflow

1. POST login form
1. create and bake cookie
1. issue redirect via 302

the Set-Cookie header is not sent to the browser if it only exists in the regular apache headers table.

so, to answer the crux of your question:
i am currently using the patched `CGI::Cookie` on my dev server, but have not deployed it live yet.
i have actually been bitten by this issue before, in a non-cookie context, and deployed a similar solution, which has been live for many years
```
    foreach my $header( qw( Expires Cache-Control Last-Modified Vary ) ) {
      my @vals = $r->headers_out()->get( $header );
      foreach my $val ( @vals ) {
        $r->err_headers_out()->add( $header => $val );
      }
      $r->headers_out->unset( $header );
    }
```
my intention, before deciding to put together a PR, was to use the long-form in my code, and i would have deployed that without a second thought.
i have not (directly) tested the assertion that the error headers are always sent, since the main context that i was focused on was my login form failing after replacing `Apache::Cookie` with `CGI::Cookie`, but i am pretty sure that my code that refreshes the cookie while your session is active, uses the same code path.

**Comment by leejo** [comment]
OK, sounds good 👍 I'll get this merged and deployed sometime next week.

**Comment by sherrardb** [comment]
while debugging some related code, i realized that this change may also impact `fetch()`, since it uses `$r->headers_in()`.
will try to confirm and report back.

**Pull request merged**
