### PR TITLE
include multi_param in :cgi bulk export/import

### PR DESCRIPTION
**Pull request by xblitz**
the recently created multi_param function is not included in the bulk import/export of CGI

### CODE REVIEW

**Comment by leejo** [comment]
Thanks! I'll squash merge this manually since it has a commit that breaks a test.

**Comment by xblitz** [comment]
yeah I also just fixed the tests, I hadn't realized that it tested the number of functions exported..

**Comment by leejo** [comment]
> yeah I also just fixed the tests, I hadn't realized that it tested the number of functions exported..

If you squash merge this into another branch or do an interactive rebase of the branch to combine the commits (the force push) i can merge here - i try to avoid any single commit to master breaking any tests where possible.

**Comment by xblitz** [comment]
ok.. will do!   trying to get used to doing pull-request, its a good exercise for me ;)

**Comment by leejo** [comment]
> ok.. will do! trying to get used to doing pull-request, its a good exercise for me ;)

No problem, happy to have PRs :)

**Pull request closed without merging**
